SwEnt-Project-G18/SwEntApp

app/build.gradle.kts, app/src/main/java/com/github/se/gomeet/EventFirebaseConnection.kt, app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/Create.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt, app/src/main/java/com/github/se/gomeet/ui/navigation/BottomNavigationMenu.kt, app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt, app/src/main/java/com/github/se/gomeet/ui/theme/Color.kt, app/src/main/java/com/github/se/gomeet/ui/theme/Theme.kt, app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
**Description:**
This pull request introduces several enhancements to improve the functionality and aesthetic appeal of our event management application. Key updates include the addition of an image uploading feature for event creation, UI enhancements for better dark mode support, fixes to the navigation bar's dynamic updating, and system UI adjustments for a more integrated fullscreen experience. These changes aim to refine user interactions and ensure a cohesive visual experience across the app.
**Features and Improvements:**
**Image Addition in Event Creation:** Implemented a feature allowing users to add images when creating events. This includes:
- An "Add Image" button within the event creation screen, enabling users to select and preview images from their device.
- The selected …
=> S3 Event Creation Image Feature and UI Enhancements

app/src/androidTest/java/com/github/se/gomeet/ui/ExploreTest.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
Added tests for the explore screen.
Currently only tests that the map is correctly displayed.
=> S3 explore tests

.github/workflows/build-release-apk.yml, app/build.gradle.kts, app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
Quick bugfix for bug accidentally introduced into main branch
=> Removed leading space in WelcomeScreen in ' Create account'

app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt, app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
This pull request introduces the newly designed UI for the profiles of other users, meticulously crafted to match the layouts provided in our Figma designs. This update enhances the visual appeal and consistency of user interfaces across our platform.
- **UI Design Implementation**: The UI for other users' profile pages has been completely redesigned to align with the Figma design specifications. This includes updates to layout, color schemes, and typography.
- **Responsive Design**: The profile page has been optimized to ensure responsiveness across various devices and screen sizes, maintaining design integrity.
Here is a screenshot showcasing the updated user profile UI:
=> S5 UI others profile

app/src/main/java/com/github/se/gomeet/ui/mainscreens/Events.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
- adding back what was removed in a previous merge: changes from pull requests #51, #52, #53 and #54 should now all be included
=> S5 fix merge issues

app/build.gradle.kts, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/ExploreTest.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt, app/src/main/res/drawable/location_icon.xml
- The map can now displays the user's current location and will be centered at that position when opening the Explore tab
- For now the user's current location is refreshed every 5 seconds
- If the user doesn't give access to their location, the camera will be set to some default location 
- Added a button to bring the camera back to the user's current location
- Fixed an issue where clicking on the Explore tab while already in Explore would cause the map to not reload properly
- Added a CircularProgressIndicator while the map is loading
https://github.com/SwEnt-Project-G18/SwEntApp/assets/125990940/f8d15c02-b60c-4cec-a719-d1ddd0a1c965
=> S5 display current location on map

app/src/androidTest/java/com/github/se/gomeet/screens/CreateEventScreen.kt, app/src/androidTest/java/com/github/se/gomeet/screens/CreateScreen.kt, app/src/androidTest/java/com/github/se/gomeet/screens/LoginScreen.kt, app/src/androidTest/java/com/github/se/gomeet/screens/TrendsScreen.kt, app/src/androidTest/java/com/github/se/gomeet/screens/WelcomeScreenScreen.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt, app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Made changes to CreateEvent:
- Added location suggestions when the user inputs a location. To make the implementation possible, the functions location and locationHelper in EventViewModel were modified to be able to fetch an arbitrary number of locations instead of only one
- Fixed a small issue where the "View selected image" text wasn't showing in dark mode
=> S5 location suggestions

app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt, app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/RegisterScreenTest.kt, app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt, app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/authentication/SignInState.kt, app/src/main/java/com/github/se/gomeet/model/repository/UserRepository.kt, app/src/main/java/com/github/se/gomeet/model/user/GoMeetUser.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/RegisterScreen.kt, app/src/main/java/com/github/se/gomeet/viewmodel/AuthViewModel.kt, app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
**Overview:**
This PR introduces several enhancements to the registration screen of our application. It adds new input fields for capturing more detailed user information during the registration process and ensures that this information is properly synced with Firebase.
**Details of Changes:**
1. **Added New Fields:**
- **First Name:** Allows the user to enter their first name.
- **Last Name:** Allows the user to enter their last name.
- **Username:** Users can now choose a unique username during registration.
- **Country:** Users can select or input their country of residence.
- **Phone Number:** Adds the capability for users to enter their phone number.
2. **Firebase Integration:**
- All the new fields are now fully integrated with Firebase. This means that as soon as a user completes …
=> S6 Register Screen Enhancements

app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt, app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
This PR introduces the implementation of the logic for the EditProfile screen, meaning the user when he adds new values to the fields on the EditProfile screen and clicks on the button `Done`, the new information written by the user will be now updated for his account and the updates are synchronized with Firebase.
=> Logic for the EditProfile synchronized with Firebase

app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/AddParticipantsTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt
added tests for AddParticipants and EditProfile
=> s6 improve coverage

.github/workflows/build-release-apk.yml
Modified the yml file to allow building a signed apk
=> changed yml file to allow signing the apk.

app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt
Disabled post button in CreateEvent screen until all fields are full.
=> Patch: event with empty description crashes app

app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
Fix broken navigation for Notifications screen
=> S6 notifications enhancement

app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfileTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt, app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt
This pull request introduces updates to the Profile screen of the SwEntApp by integrating the EventViewModel to fetch and display events directly created by the user. This change aims to showcase the real events created by the user in their Profile, which previously utilized placeholders.
The list of events displayed in the Events screen will eventually be removed.
Key Points:
- Event Display on Profile: Users can now see their events listed directly on their Profile screen. This implementation uses the EventViewModel to pull relevant event data.
- Code Enhancements: Updates include adjustments to various test files and main activity components to support the integration of the EventViewModel. This ensures that events are fetched and displayed appropriately on both individual and other …
=> S7 my events moved

app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt, app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt, app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
This pull request (PR) on the "SwEntApp" project introduces significant enhancements to the user messaging and channel navigation features within the application. It focuses on improving user interaction and message management through the following updates:
**Channel List Navigation**: A new feature is added that allows users to see a list of message channels. This is accessible via the icon at the left of the GoMeet search bar. This functionality enables users to easily navigate and switch between different discussion channels, enhancing user engagement and communication efficiency.
**Integration with `io.getstream.chat` Libraries**: The PR integrates more deeply with the Stream Chat libraries, specifically utilizing components like `ChannelsScreen` and `MessagesScreen`. These components …
=> S7-ChannelList

app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfileTest.kt, app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/MainActivity.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/LoginScreen.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterPassword.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterPfp.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterUsernameEmail.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt
- fixed issues #111 #132 #133 #96
- changed the colors of the input text of some text fields from cyan to black/white
- to make MainActivity more readable, an InitFunctions file was added and most of the code that was previously in MainActivity was moved to that file
=> S8 fix some issues

app/build.gradle.kts, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt
This PR enhances the Trends screen by adding a carousel component that displays the first five events. Additionally, the entire screen, including the carousel and event list, is now vertically scrollable as a single unit. A sort button has also been added to allow sorting events by popularity, date, or alphabetical order.
1. **Added Carousel Component**:
- Introduced `EventCarousel` composable to display the first five events in a horizontally scrolling carousel.
- The carousel automatically rotates every 10 seconds and loops back to the beginning when it reaches the end.
- Clicking on an event in the carousel navigates the user to the event info page.
2. **Enabled Vertical Scrolling for the Entire Screen**:
- Wrapped the entire content, including the carousel and the event list, in a …
=> Trends Screen UI improvement

app/build.gradle.kts, app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt, app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/create/CreateEventTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventInfoTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/events/EventsTest.kt, app/src/androidTest/java/com/github/se/gomeet/viewmodel/EventViewModelTest.kt, app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/model/event/Event.kt, app/src/main/java/com/github/se/gomeet/model/repository/EventRepository.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/DateTimePicker.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Trends.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventWidget.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/Events.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Notifications.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileEventList.kt, app/src/main/java/com/github/se/gomeet/viewmodel/EventViewModel.kt
Needed quickly to keep working
=> Merge date/time picker into branch

app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriend.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/FollowingFollowers.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt, app/src/main/java/com/github/se/gomeet/ui/navigation/NavigationAction.kt
This PR introduces the "Add Friend" screen to the GoMeet app. The following functionalities have been implemented:
1. **User List Fetching and Display**: Fetch all users from Firestore and display them in a scrollable list, excluding the current user.
2. **Search Functionality**: Implement a search bar to filter the user list based on a search query.
3. **Follow/Unfollow Users**: Allow users to follow or unfollow other users with immediate state updates.
4. **Profile Image Display**: Display user profile images in the user list.
5. **Navigation to User Profiles**: Navigate to a user's profile when clicking on a user item.
6. **UI Enhancements**: Improve the overall user experience with responsive and interactive UI components.
- **Add Friend Screen**: Created a new screen (`AddFriend`) to …
=> S8 Find User screen implementation & logic

.gitignore, app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/ProfileTest.kt, app/src/androidTest/java/com/github/se/gomeet/ui/navigation/NavigationTest.kt, app/src/androidTest/java/com/github/se/gomeet/viewmodel/UserViewModelTest.kt, app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/model/authentication/SignInState.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterPfp.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterScreen.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/EditProfile.kt, app/src/main/java/com/github/se/gomeet/viewmodel/AuthViewModel.kt, app/src/main/java/com/github/se/gomeet/viewmodel/UserViewModel.kt
Some changes made in person with Albert:
- Edit Profile Country field now shows the user country
- Uploaded Profile Picture when registering is now saved , fixes #172
=> Edit Profile Country And Profile Picture Register

app/src/androidTest/java/com/github/se/gomeet/ui/authscreens/WelcomeScreenTest.kt, app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/ui/authscreens/WelcomeScreen.kt
This PR introduces enhancements to the Google Authentication functionality within the SwEntApp. The key improvements include additional user information handling and improved user creation logic upon successful sign-in.
First sign in with Google include additional user information: `username`, `email`, `firstName`, `lastName`, and `phoneNumber`.
Fixes #164
=> First Google Authentification Enhancements

app/src/main/java/com/github/se/gomeet/ui/authscreens/register/RegisterNameCountryPhone.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/DateTimePicker.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/Explore.kt
This PR introduces some enhancements to the Explore Screen :
- Clicking on a Pin in the map shows more info about the event : the title and date of the event
- Clicking on the pin's information will take you to the event's information page.
- Clicking on an Event Card in the Slide will also take you to the event's page.
- This fixes #88 
There are also some UI enhancements on the Date Picker Composable in create event screen.
- This fixes #169
=> Explore Screen and DatePicker UI Enhancements

app/src/main/java/com/github/se/gomeet/model/Tag.kt
Added an attribute tagName to tags and updated the tag selector in consequence so tags have an meaningful value being shown.
=> Added tagName so tag showned are actual values.

app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/OthersProfile.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/profile/Profile.kt
fixed a test that was failing after the latest changes on main
=> fixed test

app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd.kt, app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd2.kt, app/src/androidTest/java/com/github/se/gomeet/endtoend/EndToEnd3.kt, app/src/androidTest/java/com/github/se/gomeet/screens/ExploreScreen.kt, app/src/main/java/com/github/se/gomeet/InitFunctions.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/Explore.kt
Made the app start in Explore instead of Explore and adjusted end to end tests so they take this change into account.
=> s9 change starting screen to explore

app/src/androidTest/java/com/github/se/gomeet/ui/mainscreens/profile/AddFriendTest.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/create/CreateEvent.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EditEvent.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/events/EventInfo.kt, app/src/main/java/com/github/se/gomeet/ui/mainscreens/explore/RowContentExplore.kt
**Summary:**
This PR introduces input sanitization to various text fields in the application. The goal is to enhance the user input validation and ensure data integrity by implementing constraints and sanitization on text fields related to event creation and editing.
**Key Changes:**
1. **Trim Trailing Spaces:**
- Added `trimEnd()` to remove trailing spaces from `titleState.value`, `descriptionState.value`, and `url.value` before submission.
2. **Price Input Validation:**
- Updated the price input field to validate the format using a regular expression, ensuring it matches the required format (up to 6 digits before the decimal and up to 2 digits after the decimal).
- Ensured the price does not exceed $1,000,000.
3. **URL Validation:**
- Added URL validation using …
=> S9 create input sanitization
